### ISSUE TITLE
Overloading ElasticSearch indexing.

### ISSUE THREAD

**Issue by moonrockfamily** [EduShareOntario/meteor-easy-search#4]
"...payload...","statusCode":429,"response":"{\"error\":{\"root_cause\":[{\"type\":\"es_rejected_execution_exception\",\"reason\":\"rejected execution of org.elasticsearch.transport.TransportService$4@57359002 on EsThreadPoolExecutor[index, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4fdde57a[Running, pool size = 16, active threads = 16, queued tasks = 200, completed tasks = 22649]]\"}],\"type\":\"es_rejected_execution_exception\",\"reason\":\"rejected execution of org.elasticsearch.transport.TransportService$4@57359002 on EsThreadPoolExecutor[index, queue capacity = 200, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@4fdde57a[Running, pool size = 16, active threads = 16, queued tasks = 200, completed tasks = 22649]]\"},\"status\":429}"}
    at respond (C:\apps\local\transcript\current\bundle\programs\server\npm\node_modules\meteor\edushareontario_easysearch-elasticsearch\node_modules\elasticsearch\src\lib\transport.js:308:15)
    at checkRespForFailure (C:\apps\local\transcript\current\bundle\programs\server\npm\node_modules\meteor\edushareontario_easysearch-elasticsearch\node_modules\elasticsearch\src\lib\transport.js:267:7)
    at HttpConnector.<anonymous> (C:\apps\local\transcript\current\bundle\programs\server\npm\node_modules\meteor\edushareontario_easysearch-elasticsearch\node_modules\elasticsearch\src\lib\connectors\http.js:165:7)
    at IncomingMessage.wrapper (C:\apps\local\transcript\current\bundle\programs\server\npm\node_modules\meteor\edushareontario_easysearch-elasticsearch\node_modules\lodash\lodash.js:4935:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by moonrockfamily** [comment]
Should back off and retry requests when getting the status 429 response.
